# Configuration des labels GitHub pour PytDm

- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: priority: high
  color: ff6b6b
  description: High priority issue

- name: priority: medium
  color: ffd93d
  description: Medium priority issue

- name: priority: low
  color: 6bcf7f
  description: Low priority issue

- name: status: in progress
  color: fbca04
  description: Work in progress

- name: status: blocked
  color: ff6b6b
  description: Blocked by another issue

- name: status: needs review
  color: 0e8a16
  description: Needs review

- name: type: feature
  color: 0e8a16
  description: New feature

- name: type: bug
  color: d73a4a
  description: Bug fix

- name: type: refactor
  color: 7057ff
  description: Code refactoring

- name: type: test
  color: ffd93d
  description: Test related

- name: type: ui
  color: e99695
  description: User interface

- name: type: performance
  color: 1d76db
  description: Performance improvement

- name: type: security
  color: ff6b6b
  description: Security related

- name: complexity: easy
  color: 6bcf7f
  description: Easy to implement

- name: complexity: medium
  color: ffd93d
  description: Medium complexity

- name: complexity: hard
  color: ff6b6b
  description: Hard to implement

- name: platform: windows
  color: 0078d4
  description: Windows specific

- name: platform: macos
  color: 000000
  description: macOS specific

- name: platform: linux
  color: fcc624
  description: Linux specific

- name: area: gui
  color: e99695
  description: Graphical user interface

- name: area: download
  color: 1d76db
  description: Download functionality

- name: area: network
  color: 7057ff
  description: Network related

- name: area: config
  color: ffd93d
  description: Configuration

- name: area: tests
  color: 6bcf7f
  description: Test suite

- name: area: docs
  color: 0075ca
  description: Documentation
